version: 2
jobs:
  build:
    docker:
      - image: python:3.7-stretch

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "~/repo/requirements.txt" }}
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make install
            # Install hadolint
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v2.6.0/hadolint-Linux-x86_64 &&\
                chmod +x /bin/hadolint

      - save_cache:
          paths:
            - ~/repo/venv
          key: v1-dependencies-{{ checksum "~/repo/requirements.txt" }}

      - run:
          name: run lint
          command: |
            . venv/bin/activate
            make lint
